version: "3"

services:
  pixie:
    container_name: pixie
    build: .
    # Host network mode is required because of how TFTP negotiates ports
    # No way around it
    network_mode: host
    restart: always
    volumes:
      # Be sure to set staticpath to "/app/data/files"
      - ./data:/app/data

