version: "3"

services:
  pixie:
    container_name: pixie
    build: .
    # Host network mode is required because of how TFTP negotiates ports
    # No way around it
    network_mode: host
    restart: always
    ports:
      - "8880:8880"
      - "69:69/udp"
    volumes:
      - ./data:/app/data

