version: "3"

services:
  pixie:
    container_name: pixie
    build: .
    restart: always
    ports:
      - "8880:8880"
      #- "69:69/udp"
      #- "65500-65600:65500-65600/udp"
    volumes:
      - ./data:/app/data

