paths:
  # Path to the user config file (recursive, lol)
  # Changing this in the user config won't actually do anything.
  # Only the value present at compile time is used
  # To actually change, use the --config-file flag
  configfile: "data/pixie.yaml"
  
  # API URL subpath
  api: "/api/v1"

  # Path to root directory for serving static files via /files
  fileserver: "data/files"

  # Path to root directory for serving script files
  # Must be inside FileServer directory
  scripts: "data/files/scripts"

  # Path to root directory for serving image files
  # Must be inside FileServer directory
  images: "data/files/images"

  # Path to the script which is served if both:
  #   1) no script is associated to the device
  #   2) no default script has been set by the user
  fallbackscript: "defaults/shell.ipxe"

  # Path to web root for Angular site (must include index.html)
  webroot: "web/dist/html"

  # Path to SQLite database file
  database: "data/pixie.db"

accessmodes:
  # Default permissions for newly created files
  filedefault: 0660

  # Default permissions for newly created directories
  dirdefault: 0770
